### ISSUE TITLE
SQLAlchemy version 1.4.36 breaks SQLModel relationships

### ISSUE THREAD

**Issue by archydeberker** [tiangolo/sqlmodel#315]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

**👆 Not quite true - this is definitely related to SQLAlchemy!**

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel


class City(SQLModel, table=True):
    name: str = Field(primary_key=True)
    heroes: "Hero" = Relationship(back_populates="city")

class Hero(SQLModel, table=True):
    name: str = Field(primary_key=True)
    city_name: Optional[str] = Field(default=None,foreign_key="city.name")
    city: Optional[City] = Relationship(back_populates="heroes",
                              sa_relationship_kwargs=dict(cascade="all,delete")
                              )


if __name__ == "__main__":

    gotham = City(name="Gotham")
    batman = Hero(name="Batman", city=gotham)

    assert batman.name == 'Batman' # This is fine
    assert batman.city == gotham # This now breaks
```

### Description

Our CI suddenly started failing, despite local SQLModel working fine. The issues turns out to be the transitive dependency on SQLAlchemy, which is weakly pinned: Github Actions pulled the latest version (`1.4.36`) and most of our tests started failing.

https://github.com/sqlalchemy/sqlalchemy/releases/tag/rel_1_4_36

The problem seems to be related to how relationships are defined, but I haven't yet dug into the SQLAlchemy changes enough to understand why that is.

I'm opening this issue chiefly to help anybody else who is confused by why suddenly their tests are failing. I'm happy to help fix it if it's affecting others too. 

For the time being we have just pinned `SQLAlchemy==1.4.34` in our `requirements.txt`.

### Operating System

Linux, macOS

### Operating System Details

Replicated locally and on Github Actions, both running in Docker

### SQLModel Version

0.0.6

### Python Version

3.9.10

### Additional Context

We were previously running SQLAlchemy 1.4.34 locally and that works fine. Pinning to 1.4.36 breaks SQLModel.

**Comment by antont** [comment]
We pinned to 1.4.35, in our fork of sqlmodel. Happened to have that locally as upgraded recently and hadn't had problems. Ran into this same this afternoon.

**Comment by JLHasson** [comment]
Same issue here, pinning to 1.4.35 resolved

**Comment by byrman** [comment]
It seems related to this recent change:
```
class DeclarativeMeta(
    _DynamicAttributesType, inspection.Inspectable["Mapper[Any]"]
):
    metadata: MetaData
    registry: "RegistryType"

    def __init__(
        cls, classname: Any, bases: Any, dict_: Any, **kw: Any
    ) -> None:
        # use cls.__dict__, which can be modified by an
        # __init_subclass__() method (#7900)
        dict_ = cls.__dict__  # This line is the culprit?!
```
https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/orm/decl_api.py#L114

**Comment by byrman** [comment]
Not sure if this is a sustainable fix, I don't know how to leverage `__init_subclass__`, but adding 1 line after [here](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/main.py#L371) makes things work again:
```
...
dict_used[rel_name] = rel_value
setattr(cls, rel_name, rel_value)  # Quick fix?
```

**Comment by jossefaz** [comment]
The SQLAlchemy maintainers confirmed that this is the issue, and also suggested a fix : https://github.com/sqlalchemy/sqlalchemy/discussions/7972#discussioncomment-2655517

**Comment by byrman** [comment]
The fix I suggested is backwards compatible. Shall I make a pull request or is there more to it than setting `rel_name` on the `cls`?

**Comment by byrman** [comment]
Let me know if this can be improved upon: https://github.com/tiangolo/sqlmodel/pull/322.

**Comment by maresb** [comment]
For reference, the actual error message is:

```python
AttributeError: 'SomeModelWithRelationshipAttribute' object has no attribute 'the_relationship_attribute'
```

**Comment by eddywee** [comment]
thank you @archydeberker  !! after hours of debugging i found this issue pinned the version and it works now! <3 thank you!

**Comment by cuamckuu** [comment]
I need to downgrade SQLalchemy in `requirements.txt` to `SQLAlchemy==1.4.35` to make relationships work

**Comment by AlanSBPerkins** [comment]
The issue remains with SQLAlchemy version 1.4.37

**Comment by Hultner** [comment]
I also ran into this issue, I have another dependency which requires SQLAlchemy > 1.4.36 which makes this quite cumbersome for me. Luckily it's just a side project which I'm using to evaluate viability of using SQLModel to reduce duplication.

**Comment by cisaacstern** [comment]
Echoing that we are also seeing this issue in our project. Pinning to sqlalchemy==1.4.35 fixes the problem. All SQLAlchemy versions > 1.4.35 break relationships. @andersy005, I'll make a note on our repo to follow this issue, and release the hard SQLAlchemy pin after this is resolved upstream.

**Comment by tiangolo** [comment]
Thanks for the report @archydeberker! :nerd_face: 

And thanks for the discussion everyone! This was solved by @byrman in https://github.com/tiangolo/sqlmodel/pull/322.

It will be available in the next version, SQLModel `0.0.7`, released in the next hours. :rocket:

**Comment by burnhamd** [comment]
Seems like this issue may still be there when inheritance is used.  

Modifying the code above

```
from typing import Optional

from sqlmodel import Field, Relationship, SQLModel


class CityBase(SQLModel, table=True):
    name: str
    heroes: "Hero" = Relationship(back_populates="city")

class City(CityBase): 
    id: Optional[int] = Field(default=None, primary_key=True)

class Hero(SQLModel, table=True):
    name: str = Field(primary_key=True)
    city_name: Optional[str] = Field(default=None,foreign_key="city.name")
    city: Optional[City] = Relationship(back_populates="heroes",
                              sa_relationship_kwargs=dict(cascade="all,delete")
                              )


if __name__ == "__main__":

    gotham = City(name="Gotham")
    batman = Hero(name="Batman", city=gotham)

    assert batman.name == 'Batman' # This is fine
    assert batman.city == gotham # This now breaks
```

Not sure if this was not working before since I am new to the project.

**Comment by mathieu-lemay** [comment]
I can still reproduce the issue with `SQLModel==0.0.8` and `SQLAlchemy==1.4.41`

```python
from sqlalchemy import ForeignKeyConstraint
from sqlalchemy.orm import RelationshipProperty, selectinload
from sqlmodel import Field, Relationship, SQLModel, select


class Parent(SQLModel, table=True):
    __tablename__ = "parents"

    # The keys are set up this way
    parent_id: int = Field(primary_key=True)
    name: str

    children: list["Child"] = Relationship(
        sa_relationship=RelationshipProperty(
            "Child",
            back_populates="parent",
        )
    )


class Child(SQLModel, table=True):
    __tablename__ = "children"
    __table_args__ = (
        ForeignKeyConstraint(
            ["parent_id"],
            [f"{Parent.__tablename__}.parent_id"],
            ondelete="CASCADE",
        ),
    )

    child_id: int = Field(primary_key=True)
    parent_id: int
    name: str

    parent: Parent = Relationship(
        sa_relationship=RelationshipProperty(
            "Parent",
            cascade="all, delete",
            back_populates="children",
        )
    )


stmt = select(Parent).options(selectinload(Parent.children))
```

Running it gives the following error:

```
Traceback (most recent call last):
  File "/home/mathieu/sqlmodelbug/main2.py", line 46, in <module>
    stmt = select(Parent).options(selectinload(Parent.children))
AttributeError: type object 'Parent' has no attribute 'children'
```

It works fine with `SLQAlchemy==1.4.35`

**Comment by byrman** [comment]
Indeed, if `sa_relationship` is defined, my naive fix is left untouched due to these [lines](https://github.com/tiangolo/sqlmodel/blob/main/sqlmodel/main.py#L330):
```
            for rel_name, rel_info in cls.__sqlmodel_relationships__.items():
                if rel_info.sa_relationship:
                    # There's a SQLAlchemy relationship declared, that takes precedence
                    # over anything else, use that and continue with the next attribute
                    dict_used[rel_name] = rel_info.sa_relationship
                    continue  # Will not reach fix!
```
Sorry I missed that path! It needs to be addressed, of course, but perhaps you can use this as a workaround:
```
class Parent(SQLModel, table=True):
    children: list["Child"] = Relationship(back_populates="parent")
```
```
class Child(SQLModel, table=True):
    parent: Parent = Relationship(back_populates="children")
```

**Comment by byrman** [comment]
@mathieu-lemay, I made a pull request that covers your case as well: https://github.com/tiangolo/sqlmodel/pull/461. I still have to add a test though.
